[project]
name = "nerf-investigation"
version = "0.0.1"
description = ""
requires-python = "==3.7.*"

dependencies = [
    "tensorflow-gpu==1.15",
    "numpy",
    "matplotlib",
    "imageio==2.8.0",
    "imageio-ffmpeg",
    "configargparse",
    "protobuf==3.20.3", 
]
